### ISSUE TITLE
Input ending with a new line causes read error

### ISSUE THREAD

**Issue by PoneyClairDeLune** [ltgcgo/rochelle#1]
```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'subarray')
    at Object.pull (https://jsr.io/@ltgc/rochelle/0.2.2/dist/textRead.mjs:1:963)
    at eventLoopTick (ext:core/01_core.js:175:7)
```

**Comment by PoneyClairDeLune** [comment]
Bug fixed as of https://github.com/ltgcgo/rochelle/commit/fc860c5e1c90577a1661160c021f2563b0e5ca0b .
